arrayNeg5 = ["très mal", "désespéré","désespérée","abattu","abattue","anéanti","anéantie","effondré","effondrée","dévasté","dévastée","brisé","brisée","au bout du rouleau","à bout","perdu","perdue","sans espoir","désillusionné","désillusionnée","accablé","accablée","écrasé","écrasée","misérable","malheureux","malheureuse","désolé","désolée","terrassé","terrassée","anéanti moralement","au plus mal","horriblement mal","très mal","catastrophique","catastrophé","catastrophée","détruit","détruite","vidé","vidée","épuisé moralement","épuisée moralement","déprimé","déprimée","dépression","dépressif","dépressive","sombre","désenchanté","désenchantée","désorienté","désorientée","en détresse","angoissé","angoissée","terrifié","terrifiée","paniqué","paniquée","au fond du trou","je n'en peux plus","je craque","je suis au bout","je me sens détruit","je me sens brisé","je vais très mal"]

arrayNeg3 = ["triste","tristement","mal","pas bien","déçu","déçue","découragé","découragée","démotivé","démotivée","frustré","frustrée","contrarié","contrariée","préoccupé","préoccupée","inquiet","inquiète","stressé","stressée","tendu","tendue","nerveux","nerveuse","morose","mélancolique","fatigué moralement","fatiguée moralement","lassé","lassée","épuisé","épuisée","vidé","vidée","irritable","agacé","agacée","énervé","énervée","bouleversé","bouleversée","déprimé","déprimée","soucieux","soucieuse","pessimiste","désorienté","désorientée","confus","confuse","déstabilisé","déstabilisée","accablé","accablée","j'ai le moral bas","je me sens mal","je suis triste","je suis inquiet","je suis stressé","je suis stressée","je suis découragé","je suis découragée","je suis frustré","je suis frustrée","ça ne va pas","pas terrible","pas la forme","pas au mieux","journée difficile","c'est compliqué","j'en ai marre","je suis à cran","je me sens seul","je me sens seule"]

arrayNeg1 = [ "dommage", "un peu", "pas trop", "bof",  "mou",  "fatigué",  "fatiguée",  "las",  "lasse",  "un peu fatigué",  "un peu fatiguée",  "un peu stressé",  "un peu stressée",  "un peu inquiet",  "un peu inquiète",  "préoccupé",  "préoccupée",  "pensif",  "pensive",  "mitigé",  "mitigée",  "indifférent",  "indifférente",  "dubitatif",  "dubitative",  "incertain",  "incertaine",  "perplexe",  "hésitant",  "hésitante",  "contrarié",  "contrariée",  "agacé",  "agacée",  "ennuyé",  "ennuyée",  "lassé",  "lassée",  "morne",  "nostalgique",  "sceptique",  "réservé",  "réservée", "je suis fatigué","je suis fatiguée", "pas au top",  "pas en forme",  "pas super",  "pas génial",  "pas terrible",  "sans plus",  "comme ci comme ça",  "moyen",  "ça peut aller",  "ça va moyen",  "ça va bof",  "un peu perdu",  "un peu perdue",  "légèrement stressé",  "légèrement stressée",  "légèrement inquiet",  "légèrement inquiète",  "fatigué mais ça va",  "fatiguée mais ça va",  "pas très motivé",  "pas très motivée",  "peu motivé",  "peu motivée",  "dans le doute",  "pas totalement convaincu",  "pas totalement convaincue",  "un peu contrarié",  "un peu contrariée"]

arrayPos5 = ["parfait", "parfaite", "parfaitement", "extrêmement", "au top", "super", "très heureux",  "très heureuse",  "ravi",  "ravie",  "enchanté",  "enchantée",  "comblé",  "comblée",  "épanoui",  "épanouie",  "rayonnant",  "rayonnante",  "aux anges",  "sur un nuage",  "au paradis",  "euphorique",  "extatique",  "jubilaire",  "transporté de joie",  "transportée de joie",  "fou de joie",  "folle de joie",  "radieux",  "radieuse",  "exalté",  "exaltée",  "surexcité",  "surexcitée",  "enthousiaste",  "emballé",  "emballée",  "gonflé à bloc",  "motivé à fond",  "plein d'énergie",  "pleine d'énergie",  "au top",  "au sommet",  "incroyablement bien",  "formidable",  "fantastique",  "extraordinaire",  "génial",  "exceptionnel",  "merveilleux",  "merveilleuse",  "parfaitement bien",  "au meilleur de ma forme",  "je vais super bien",  "je vais extrêmement bien",  "je suis aux anges",  "je suis sur un nuage",  "je suis comblé",  "je suis comblée",  "je suis épanoui",  "je suis épanouie",  "je suis ravi",  "je suis ravie",  "je suis heureux",  "je suis heureuse",  "je suis euphorique",  "je suis exalté",  "je suis exaltée",  "je me sens invincible",  "je me sens fantastique",  "je me sens formidable",  "je déborde d'énergie",  "je suis en pleine forme",  "tout va merveilleusement bien",  "tout va parfaitement bien",  "c'est une journée parfaite",  "c'est le bonheur",  "je suis au comble du bonheur",  "je n'ai jamais été aussi bien",  "je me sens incroyablement bien",  "je suis extrêmement motivé",  "je suis extrêmement motivée"]

arrayPos3 = [ "nickel", "cool", "bien",  "plutôt bien",  "content",  "contente",  "heureux",  "heureuse",  "satisfait",  "satisfaite",  "optimiste",  "confiant",  "confiante",  "motivé",  "motivée",  "enthousiaste",  "dynamique",  "énergique",  "en forme",  "de bonne humeur",  "joyeux",  "joyeuse",  "positif",  "positive",  "serein",  "sereine",  "apaisé",  "apaisée",  "détendu",  "détendue",  "rassuré",  "rassurée",  "encouragé",  "encouragée",  "inspiré",  "inspirée",  "fier",  "fière",  "reconnaissant",  "reconnaissante",  "plein d'espoir",  "pleine d'espoir",  "de mieux en mieux",  "ça va bien",  "ça va très bien",  "je vais bien",  "je me sens bien",  "je me sens mieux",  "je suis content",  "je suis contente",  "je suis satisfait",  "je suis satisfaite",  "je suis motivé",  "je suis motivée",  "je suis optimiste",  "je suis confiant",  "je suis confiante",  "je suis serein",  "je suis sereine",  "je suis détendu",  "je suis détendue",  "je suis de bonne humeur",  "je suis en forme",  "je me sens positif",  "je me sens positive",  "tout va bien",  "bonne journée",  "très bonne journée",  "j'ai le moral",  "j'ai le sourire",  "je suis encouragé",  "je suis encouragée",  "je me sens capable",  "je me sens fort",  "je me sens forte"]

arrayPos1 = [  "pas à me plaindre", "ça va",  "ca va",  "ça va bien",  "ca va bien", "plutot" , "ok", "plutôt bien",  "pas mal",  "assez bien",  "correct",  "correcte",  "bien",  "okay",  "ok",  "d'accord",  "tranquille",  "calme",  "posé",  "posée",  "serein",  "sereine",  "détendu",  "détendue",  "apaisé",  "apaisée",  "reposée",  "reposé",  "stable",  "équilibré",  "équilibrée",  "confortable",  "à l'aise",  "pas trop mal",  "ça peut aller",  "sympa",  "agréable",  "bien dans l'ensemble",  "ça se passe bien",  "ça va plutôt bien",  "je vais bien",  "je me sens bien",  "je me sens plutôt bien",  "je suis calme",  "je suis serein",  "je suis sereine",  "je suis détendu",  "je suis détendue",  "je suis tranquille",  "je suis reposé",  "je suis reposée",  "rien à signaler",  "tout va bien",  "ça va mieux",  "mieux",  "un peu mieux",  "assez serein",  "assez sereine",  "assez détendu",  "assez détendue",  "de bonne disposition",  "plutôt satisfait",  "plutôt satisfaite"]



message = input("Comment vous sentez-vous aujourd'hui? ").lower()

compteurPositif = 0
compteurNegatif = 0
for mot in arrayNeg5:
    if mot in message: compteurNegatif+=5
for mot in arrayNeg3:
    if mot in message: compteurNegatif+=3
for mot in arrayNeg1:
    if mot in message: compteurNegatif+=1
for mot in arrayPos5:
    if mot in message: compteurPositif+=5
for mot in arrayPos3:
    if mot in message: compteurPositif+=3
for mot in arrayPos1:
    if mot in message: compteurPositif+=1


print(compteurPositif)
print(compteurNegatif)  
if compteurPositif > compteurNegatif : print('Vous êtes de bonne humeur !')
elif compteurPositif < compteurNegatif : print('Votre humeur n\'est pas au top')
else : print("Votre humeur est plutôt neutre")